name: Run Python script

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Important: This allows your job to access all commits
          token: ${{ secrets.GH_PAT }}  # Use the PAT for authentication

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python scraper.py

      - name: Commit and push if it changed
        run: |
          git diff
          git config --local user.email "alifarhad557@gmail.com"
          git config --local user.name "ali-farhad"
          git commit -m "Update previous_message.txt" -a || echo "No changes to commit"
          git push
